### ISSUE TITLE
Game Crash Related to UnitedCallouts

### ISSUE THREAD

**Issue by alexp9982** [sEbi3/UnitedCallouts#1]
One of the callouts in UnitedCallouts caused the crashing of the LSPDFR plugin at the end of the callout. Included is the RagePluginLog.log.

Before anyone asks, yes, I have all the requirements.
[RagePluginHook.log](https://github.com/sEbi3/UnitedCallouts/files/4675441/RagePluginHook.log)

Main crash thread: 
```
[5/25/2020 1:57:18 AM.864] LSPD First Response: STP: TOW SERVICE IS FULLY DISMISSED
[5/25/2020 1:57:23 AM.401] LSPD First Response: 
[5/25/2020 1:57:23 AM.401] LSPD First Response: ==============================
[5/25/2020 1:57:23 AM.401] LSPD First Response: UNHANDLED EXCEPTION DURING GAME FIBER TICK
[5/25/2020 1:57:23 AM.401] LSPD First Response: ------------------------------
[5/25/2020 1:57:23 AM.401] LSPD First Response: Origin: Game fiber "Armored Person [UnitedCallouts]".
[5/25/2020 1:57:23 AM.401] LSPD First Response: ------------------------------
[5/25/2020 1:57:23 AM.401] LSPD First Response: Exception type: Rage.Exceptions.InvalidHandleableException
[5/25/2020 1:57:23 AM.401] LSPD First Response: Exception message: Operation is not valid because the specified  Rage.Ped is invalid.
[5/25/2020 1:57:23 AM.401] LSPD First Response: ------------------------------
[5/25/2020 1:57:23 AM.401] LSPD First Response: Inner exceptions:
[5/25/2020 1:57:23 AM.401] LSPD First Response: ------------------------------
[5/25/2020 1:57:23 AM.401] LSPD First Response: Stack trace:
[5/25/2020 1:57:23 AM.401] LSPD First Response: at Rage.Entity.get_IsDead()
[5/25/2020 1:57:23 AM.401] at UnitedCallouts.Callouts.ArmoredPerson.<Process>b__24_0()
[5/25/2020 1:57:23 AM.401] at Rage.GameFiber.Main()
[5/25/2020 1:57:23 AM.401] LSPD First Response: ==============================
[5/25/2020 1:57:23 AM.401] LSPD First Response: 
[5/25/2020 1:57:23 AM.404] LSPD First Response: [FATAL] Forced termination
[5/25/2020 1:57:23 AM.405] LSPD First Response: [TRACE] Released 0 entities from DefaultContentManager
[5/25/2020 1:57:25 AM.252] LSPD First Response: [INFO] LSPDFR has shut down
[5/25/2020 1:57:25 AM.910] LSPD First Response: All signs removed
[5/25/2020 1:57:26 AM.444] LSPD First Response: Error occured in mechanic request: Thread was being aborted.

```

If you have any additional questions you would like answered, ask away, and I'll try to respond ASAP.

**Comment by sEbi3** [comment]
Thank you for reporting it.
The "Rage.Ped is invalid" error is already a known bug.
I will try to fix it for the next version. 

Have a nice day! :)

**Comment by alexp9982** [comment]
In order to avoid this crash, do I need to disable the plugin, or maybe disable a few callouts? If so, which callouts?
