### ISSUE TITLE
ATMActivity bug crashes LSPDFR

### ISSUE THREAD

**Issue by TiebeVercoutter** [sEbi3/UnitedCallouts#2]
Hi, after I arrested the ped from the ATMActivity my LSPDFR crashed. I'm not sure if the bug is from UnitedCallouts or something else.
```
[7/6/2021 11:55:36 AM.134] LSPD First Response: Creating ATMActivity from UnitedCallouts.Callouts.ATMActivity, UnitedCallouts, Version=1.5.7.6, Culture=neutral, PublicKeyToken=null
[7/6/2021 11:55:36 AM.134] LSPD First Response: [TRACE] Callout created:  #2
[7/6/2021 11:55:36 AM.136] LSPD First Response: GetAudioFileForAction: No file found for: STREET_SAN_ANDREAS_AVE
[7/6/2021 11:55:39 AM.226] LSPD First Response: UnitedCallouts Log: ATMActivity callout accepted.
[7/6/2021 11:55:39 AM.282] LSPD First Response: [TRACE] Cleaning UI
[7/6/2021 11:55:39 AM.282] LSPD First Response: [TRACE] User accepted callout
[7/6/2021 11:55:47 AM.668] LSPD First Response: [TRACE] Player is close, starting pursuit
[7/6/2021 11:55:47 AM.670] LSPD First Response: [TRACE] Created new chase
[7/6/2021 11:55:47 AM.672] LSPD First Response: [TRACE] Assigned ped to ChaseHost #1 (GameplayMandatory)
[7/6/2021 11:55:47 AM.687] LSPD First Response: [TRACE] Suspect added to chase
[7/6/2021 11:55:47 AM.703] LSPD First Response: [TRACE] Starting chase
[7/6/2021 11:55:47 AM.703] LSPD First Response: [TRACE] Thread ChaseHost #1 initialized
[7/6/2021 11:55:47 AM.772] LSPD First Response: [TRACE] Extended route by 20
[7/6/2021 11:55:47 AM.791] LSPD First Response: [TRACE] Player now monitoring Paul White
[7/6/2021 11:55:47 AM.796] LSPD First Response: [TRACE] Found new close chase
[7/6/2021 11:55:48 AM.271] LSPD First Response: [TRACE] Extended route by 20
[7/6/2021 11:55:50 AM.140] LSPD First Response: [TRACE] Removing ped from PoliceStation #3 (Ambient)
[7/6/2021 11:55:50 AM.140] LSPD First Response: [TRACE] Removing ped from PoliceStation #3 (Ambient)
[7/6/2021 11:55:50 AM.140] LSPD First Response: [TRACE] Removing ped from PoliceStation #3 (Ambient)
[7/6/2021 11:55:50 AM.140] LSPD First Response: [TRACE] Removing ped from PoliceStation #3 (Ambient)
[7/6/2021 11:55:50 AM.140] LSPD First Response: [TRACE] Removing ped from PoliceStation #3 (Ambient)
[7/6/2021 11:55:50 AM.140] LSPD First Response: [TRACE] Released 0 entities from PoliceStation #3 Content Manager
[7/6/2021 11:55:50 AM.140] LSPD First Response: [TRACE] Instance cleaned (PoliceStation #3)
[7/6/2021 11:55:50 AM.151] LSPD First Response: [TRACE] Ped Julianne Fox has become idle again
[7/6/2021 11:55:50 AM.151] LSPD First Response: [TRACE] Ped Nicole Thomas has become idle again
[7/6/2021 11:55:50 AM.151] LSPD First Response: [TRACE] Ped Markus Fortuna has become idle again
[7/6/2021 11:55:50 AM.151] LSPD First Response: [TRACE] Ped Winston Bobs has become idle again
[7/6/2021 11:55:50 AM.151] LSPD First Response: [TRACE] Ped Jason Stansfield has become idle again
[7/6/2021 11:55:51 AM.859] LSPD First Response: [TRACE] Too far away from recent closest chase
[7/6/2021 11:55:54 AM.485] LSPD First Response: Added ambient event fibers to cleanup
[7/6/2021 11:55:59 AM.815] LSPD First Response: [TRACE] Extended route by 20
[7/6/2021 11:56:06 AM.612] LSPD First Response: [TRACE] Extended route by 20
[7/6/2021 11:56:16 AM.877] LSPD First Response: [TRACE] Extended route by 20
[7/6/2021 11:56:18 AM.048] LSPD First Response: [TRACE] Visual lost event fired
[7/6/2021 11:56:21 AM.805] LSPD First Response: [TRACE] Created new chase
[7/6/2021 11:56:21 AM.805] LSPD First Response: [TRACE] Assigned ped to Chase #2 (GameplayMandatory)
[7/6/2021 11:56:21 AM.805] LSPD First Response: [TRACE] Took ownership of suspect for chase
[7/6/2021 11:56:21 AM.805] LSPD First Response: [TRACE] Suspect added to chase
[7/6/2021 11:56:21 AM.808] LSPD First Response: [TRACE] Pursuit menu was reset.
[7/6/2021 11:56:21 AM.815] LSPD First Response: [TRACE] Starting chase
[7/6/2021 11:56:21 AM.871] LSPD First Response: [TRACE] [CONSOLE] System.NotImplementedException: The method or operation is not implemented.
[7/6/2021 11:56:21 AM.871] at ZWKDKPbcEMfoSLHhYEDJlBtfgCrjA.fjjvDxgheIioYALivpoTQOfjGmIFb(zdVALJOReSsVcMsBbTLeJrTaHoGr ) in E:\GTA V\LSPD First Response\LSPD First Response\Engine\Scripting\AI\Cooldown.cs:line 48
[7/6/2021 11:56:21 AM.871] at OxDzGVKOGSlBzjsrHpOHqzYFqdCI.ddlPwaMVHCJjadDNEhgdNIqcfstu(zdVALJOReSsVcMsBbTLeJrTaHoGr )
[7/6/2021 11:56:21 AM.871] at OvFYWyIKfkzEQmjDPgLpNhfgiuVl.fjjvDxgheIioYALivpoTQOfjGmIFb(zdVALJOReSsVcMsBbTLeJrTaHoGr ) in E:\GTA V\LSPD First Response\LSPD First Response\Mod\BackupManager.cs:line 848
[7/6/2021 11:56:21 AM.871] LSPD First Response: [TRACE] [CONSOLE] System.NotImplementedException: The method or operation is not implemented.
[7/6/2021 11:56:21 AM.871] at UWQcZjHNwbGmwGVWwMVofEzEeAzIB.fjjvDxgheIioYALivpoTQOfjGmIFb(zdVALJOReSsVcMsBbTLeJrTaHoGr ) in E:\GTA V\LSPD First Response\LSPD First Response\Engine\Scripting\AI\CooldownFail.cs:line 48
[7/6/2021 11:56:21 AM.871] at OxDzGVKOGSlBzjsrHpOHqzYFqdCI.ddlPwaMVHCJjadDNEhgdNIqcfstu(zdVALJOReSsVcMsBbTLeJrTaHoGr )
[7/6/2021 11:56:21 AM.871] at SGUvRjgmLjQGCJhXWAZyXiYdOQNh.fjjvDxgheIioYALivpoTQOfjGmIFb(zdVALJOReSsVcMsBbTLeJrTaHoGr ) in E:\GTA V\LSPD First Response\LSPD First Response\Mod\BackupManager.cs:line 772
[7/6/2021 11:56:21 AM.917] LSPD First Response: [TRACE] Player now monitoring Josh Cassidy
[7/6/2021 11:56:22 AM.915] LSPD First Response: [TRACE] Invoking PedGainedVisual
[7/6/2021 11:56:23 AM.659] LSPD First Response: [TRACE] Extended route by 20
[7/6/2021 11:56:23 AM.920] LSPD First Response: [TRACE] InvokePedRegainedVisualOfSuspectEvent
[7/6/2021 11:56:23 AM.920] LSPD First Response: [TRACE] Visual regained event fired
[7/6/2021 11:56:27 AM.062] LSPD First Response: [TRACE] Extended route by 20
[7/6/2021 11:56:27 AM.861] LSPD First Response: UB: REQUESTED TYPE: LocalPatrol
[7/6/2021 11:56:27 AM.863] LSPD First Response: UB: DETECTED ZONE: PBOX
[7/6/2021 11:56:27 AM.863] LSPD First Response: UB: DETECTED COUNTY: LosSantosCity
[7/6/2021 11:56:27 AM.903] LSPD First Response: GetAudioFileForAction: No file found for: STREET_SAN_ANDREAS_AVE
[7/6/2021 11:56:27 AM.912] LSPD First Response: UB: STARTED PURSUIT >> OSB-0
[7/6/2021 11:56:28 AM.044] LSPD First Response: [TRACE] TaskCopPlayRadioAction Initialize()
[7/6/2021 11:56:28 AM.135] LSPD First Response: [TRACE] Visual lost longer
[7/6/2021 11:56:28 AM.964] LSPD First Response: [TRACE] Assigned ped to Chase #2 (GameplayMandatory)
[7/6/2021 11:56:28 AM.964] LSPD First Response: [TRACE] Took ownership of cop for chase
[7/6/2021 11:56:28 AM.964] LSPD First Response: [WARN] Added cop without proper cop data
[7/6/2021 11:56:28 AM.964] LSPD First Response: [TRACE] New cop added without cop data!
[7/6/2021 11:56:28 AM.964] LSPD First Response: [TRACE] Brad Sims (MP_M_FREEMODE_01) was set as a cop
[7/6/2021 11:56:28 AM.984] LSPD First Response: [TRACE] Cop Brad Sims reassigned to Josh Cassidy
[7/6/2021 11:56:28 AM.985] LSPD First Response: [TRACE] Cop added to chase
[7/6/2021 11:56:28 AM.997] LSPD First Response: [TRACE] Visual lost event fired
[7/6/2021 11:56:29 AM.018] LSPD First Response: [TRACE] Brad Sims now monitoring Josh Cassidy
[7/6/2021 11:56:29 AM.268] LSPD First Response: [TRACE] [CONSOLE] System.NullReferenceException: Object reference not set to an instance of an object.
[7/6/2021 11:56:29 AM.268] at DfFFcgbktlITaDPzqSriyGtgJmhEb.itrojDKJOmzddclfxIMkxrlVttfs() in E:\GTA V\LSPD First Response\LSPD First Response\Engine\Scripting\Tasks\TaskCopChasePedAdv.cs:line 1501
[7/6/2021 11:56:29 AM.268] at bEoanlazHdDEMpZQDtMCFVjDsZRH.fjjvDxgheIioYALivpoTQOfjGmIFb(zdVALJOReSsVcMsBbTLeJrTaHoGr )
[7/6/2021 11:56:30 AM.000] LSPD First Response: [TRACE] InvokePedRegainedVisualOfSuspectEvent
[7/6/2021 11:56:30 AM.000] LSPD First Response: [TRACE] Visual regained event fired
[7/6/2021 11:56:30 AM.805] LSPD First Response: [TRACE] Extended route by 20
[7/6/2021 11:56:30 AM.805] LSPD First Response: [TRACE] Extended route by 20
[7/6/2021 11:56:31 AM.972] LSPD First Response: [TRACE] Brad Sims (MP_M_FREEMODE_01) entered combat with target: Josh Cassidy (A_M_Y_BEVHILLS_02)
[7/6/2021 11:56:32 AM.048] LSPD First Response: [TRACE] Aborting CopPlayRadioAction: Timed out
[7/6/2021 11:56:32 AM.049] LSPD First Response: [TRACE] TaskCopPlayRadioAction aborted
[7/6/2021 11:56:34 AM.052] LSPD First Response: [TRACE] Josh Cassidy (A_M_Y_BEVHILLS_02) was damaged.
[7/6/2021 11:56:34 AM.056] LSPD First Response: [TRACE] Ped damaged by player with RunOverByCar at RightThigh. Could see player: False
[7/6/2021 11:56:40 AM.264] LSPD First Response: [TRACE] Aborting AnimatedSwitchWeapon: Animation stopped.
[7/6/2021 11:56:41 AM.118] LSPD First Response: [TRACE] Josh Cassidy (A_M_Y_BEVHILLS_02) was damaged.
[7/6/2021 11:56:41 AM.119] LSPD First Response: [TRACE] Ped damaged by player with Pistol at RightUpperArm. Could see player: False
[7/6/2021 11:56:43 AM.847] HAS WEAPON
[7/6/2021 11:56:43 AM.862] LSPD First Response: [TRACE] Thread PlayerArrest #1 initialized
[7/6/2021 11:56:47 AM.336] LSPD First Response: [TRACE] Invoking PedGainedVisual
[7/6/2021 11:56:48 AM.342] LSPD First Response: [TRACE] InvokePedRegainedVisualOfSuspectEvent
[7/6/2021 11:56:52 AM.201] LSPD First Response: [TRACE] Brad Sims (MP_M_FREEMODE_01) left combat.
[7/6/2021 11:56:54 AM.368] LSPD First Response: [TRACE] InvokePedRegainedVisualOfSuspectEvent
[7/6/2021 11:56:58 AM.260] LSPD First Response: [TRACE] Brad Sims (MP_M_FREEMODE_01) entered combat with target: Josh Cassidy (A_M_Y_BEVHILLS_02)
[7/6/2021 11:56:58 AM.521] LSPD First Response: [TRACE] Cleaning UI
[7/6/2021 11:56:58 AM.521] LSPD First Response: [TRACE] Released 0 entities from  #2 Content Manager
[7/6/2021 11:56:58 AM.521] LSPD First Response: [TRACE] Instance cleaned ( #2)
[7/6/2021 11:56:58 AM.528] LSPD First Response: [TRACE] No more fleeing suspects, ending chase
[7/6/2021 11:56:58 AM.531] LSPD First Response: [TRACE] Ending chase
[7/6/2021 11:56:58 AM.533] LSPD First Response: [TRACE] TaskCopChasePedAdv::OnAbort
[7/6/2021 11:56:58 AM.534] LSPD First Response: [TRACE] Removed ped chase strategy
[7/6/2021 11:56:58 AM.535] LSPD First Response: [TRACE] Removing ped from Chase #2 (GameplayMandatory)
[7/6/2021 11:56:58 AM.535] LSPD First Response: [TRACE] Freeing cop: Brad Sims
[7/6/2021 11:56:58 AM.535] LSPD First Response: [TRACE] Cop freed
[7/6/2021 11:56:58 AM.537] LSPD First Response: [TRACE] Aborting CopChaseVisualCheck: Suspect freed
[7/6/2021 11:56:58 AM.537] LSPD First Response: [TRACE] Suspect freed
[7/6/2021 11:56:58 AM.538] LSPD First Response: [TRACE] Removing ped from Chase #2 (GameplayMandatory)
[7/6/2021 11:56:58 AM.538] LSPD First Response: [TRACE] Released 0 entities from Chase #2 Content Manager
[7/6/2021 11:56:58 AM.538] LSPD First Response: [TRACE] Instance cleaned (Chase #2)
[7/6/2021 11:56:58 AM.538] LSPD First Response: [TRACE] Ped Josh Cassidy has become idle again
[7/6/2021 11:56:58 AM.538] LSPD First Response: [TRACE] Ped Brad Sims has become idle again
[7/6/2021 11:56:58 AM.541] LSPD First Response: Contains key after add
[7/6/2021 11:56:58 AM.542] LSPD First Response: Weapon Dropped
[7/6/2021 11:56:58 AM.543] LSPD First Response: [TRACE] Cleaning UI
[7/6/2021 11:56:58 AM.543] LSPD First Response: [TRACE] ATMActivity is ending already
[7/6/2021 11:56:58 AM.543] LSPD First Response:    at System.Environment.GetStackTrace(Exception e, Boolean needFileInfo)
[7/6/2021 11:56:58 AM.543] at System.Environment.get_StackTrace()
[7/6/2021 11:56:58 AM.543] at LSPD_First_Response.Engine.BaseComponent.rinMfyMapFoIZeBXRLiieSdtbYnN() in E:\GTA V\LSPD First Response\LSPD First Response\Engine\BaseComponent.cs:line 66
[7/6/2021 11:56:58 AM.543] at LSPD_First_Response.Mod.Callouts.Callout.End() in E:\GTA V\LSPD First Response\LSPD First Response\Mod\Callouts\Callout.cs:line 217
[7/6/2021 11:56:58 AM.543] at UnitedCallouts.Callouts.ATMActivity.End()
[7/6/2021 11:56:58 AM.543] at UnitedCallouts.Callouts.ATMActivity.<Process>b__20_0()
[7/6/2021 11:56:58 AM.543] at Rage.GameFiber.Main()
[7/6/2021 11:56:58 AM.543] at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
[7/6/2021 11:56:58 AM.543] at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
[7/6/2021 11:56:58 AM.543] at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
[7/6/2021 11:56:58 AM.543] at System.Threading.ThreadHelper.ThreadStart()
[7/6/2021 11:56:58 AM.766] LSPD First Response: [TRACE] Brad Sims (MP_M_FREEMODE_01) left combat.
[7/6/2021 11:57:00 AM.818] LSPD First Response: [TRACE] A new world event should be started
[7/6/2021 11:57:00 AM.818] LSPD First Response: [TRACE] Starting world event RunLights
[7/6/2021 11:57:00 AM.819] LSPD First Response: [TRACE] Setting up world event: RunLights #1
[7/6/2021 11:57:00 AM.821] LSPD First Response: [TRACE] Failed to set up RunLights #1
[7/6/2021 11:57:00 AM.821] LSPD First Response: [TRACE] Released 0 entities from RunLights #1 Content Manager
[7/6/2021 11:57:00 AM.821] LSPD First Response: [TRACE] Instance cleaned (RunLights #1)
[7/6/2021 11:57:01 AM.217] LSPD First Response: [TRACE] Extended route by 20
[7/6/2021 11:57:01 AM.719] LSPD First Response: UB: FINISHED PURSUIT >> OSB-0 PAX-0
[7/6/2021 11:57:03 AM.227] LSPD First Response: [TRACE] Asked thread PlayerArrest #1 to abort: No reason specified
[7/6/2021 11:57:03 AM.228] LSPD First Response: [TRACE] Released 0 entities from PlayerArrest #1 Content Manager
[7/6/2021 11:57:03 AM.228] LSPD First Response: [TRACE] Instance cleaned (PlayerArrest #1)
[7/6/2021 11:57:03 AM.236] LSPD First Response: [TRACE] Thread PlayerArrest #1 has been shut down
[7/6/2021 11:57:03 AM.237] LSPD First Response: [TRACE] Assigned ped to PlayerSuspectTransportNew #1 (Blocker)
[7/6/2021 11:57:03 AM.237] LSPD First Response: [TRACE] Thread PlayerSuspectTransportNew #1 initialized
[7/6/2021 11:57:03 AM.366] LSPD First Response: [TRACE] Suspect died in player custody
[7/6/2021 11:57:03 AM.366] LSPD First Response: [TRACE] Asked thread PlayerSuspectTransportNew #1 to abort: Suspect is dead
[7/6/2021 11:57:03 AM.366] LSPD First Response: [TRACE] Removing ped from PlayerSuspectTransportNew #1 (Blocker)
[7/6/2021 11:57:03 AM.366] LSPD First Response: [TRACE] Released 0 entities from PlayerSuspectTransportNew #1 Content Manager
[7/6/2021 11:57:03 AM.366] LSPD First Response: [TRACE] Instance cleaned (PlayerSuspectTransportNew #1)
[7/6/2021 11:57:03 AM.366] LSPD First Response: [TRACE] PlayerSuspectTransportNew #1 is aborting already
[7/6/2021 11:57:03 AM.373] LSPD First Response: [TRACE] Ped Josh Cassidy has become idle again
[7/6/2021 11:57:03 AM.377] LSPD First Response: [TRACE] Thread PlayerSuspectTransportNew #1 has been shut down
[7/6/2021 11:57:03 AM.421] LSPD First Response: STP cannot take control player arrested PedRage.Exceptions.InvalidHandleableException: Operation is not valid because the specified  Rage.Ped is invalid.
[7/6/2021 11:57:03 AM.422] at Rage.Ped.Resurrect()
[7/6/2021 11:57:03 AM.422] at ‏⁬‍‬⁯⁬⁭⁮‌‬‪⁯‪‮‍⁪‎‪‪‌⁭⁯‪‪⁪⁪‭⁪‮‏⁬‌‌⁬‫‭‌‭‭⁬‮.⁬⁪‏⁭‌⁬‎‏⁬⁫‏⁬⁯‬⁪⁪‫⁭‍⁮‫‏⁫⁫‬⁭⁭⁪⁮⁮⁭⁮‮‪‬‮‏‎‌⁫‮(Ped )
[7/6/2021 11:57:03 AM.422] at ‏⁬‍‬⁯⁬⁭⁮‌‬‪⁯‪‮‍⁪‎‪‪‌⁭⁯‪‪⁪⁪‭⁪‮‏⁬‌‌⁬‫‭‌‭‭⁬‮.⁮‪⁬‮⁫⁭‍‎⁭⁫⁬​⁭​⁫⁯⁪‌‍‍‭⁯​​⁬‌‌‏⁭⁫⁬⁯‏⁫‎‬⁬‌⁭⁫‮(Ped )
[7/6/2021 11:57:03 AM.422] at ‏⁬‍‬⁯⁬⁭⁮‌‬‪⁯‪‮‍⁪‎‪‪‌⁭⁯‪‪⁪⁪‭⁪‮‏⁬‌‌⁬‫‭‌‭‭⁬‮.‍‌⁮⁯‫⁫⁫‬‎‪⁭⁬‌‮⁯⁮‬⁮⁬‮⁪‭‍‭‪‪⁯⁪‍‬‏‪⁮‮⁯⁭⁪‪⁯‮‮.‬‫⁮‏‫⁭⁭⁭⁫⁬‭⁬​‌‮⁪⁫⁮‫‬⁫⁭⁬⁭⁪‌⁮⁫‭⁭⁯‫‏‏‌⁫⁪‍‮‫‮()
[7/6/2021 11:57:03 AM.519] LSPD First Response: UB: IN STANDBY POSITION >> OSB-0 PAX-0
[7/6/2021 11:57:04 AM.637] LSPD First Response: 
[7/6/2021 11:57:04 AM.637] LSPD First Response: ==============================
[7/6/2021 11:57:04 AM.637] LSPD First Response: UNHANDLED EXCEPTION DURING GAME FIBER TICK
[7/6/2021 11:57:04 AM.637] LSPD First Response: ------------------------------
[7/6/2021 11:57:04 AM.637] LSPD First Response: Origin: Game fiber "<UNNAMED THREAD>".
[7/6/2021 11:57:04 AM.637] LSPD First Response: ------------------------------
[7/6/2021 11:57:04 AM.637] LSPD First Response: Exception type: Rage.Exceptions.InvalidHandleableException
[7/6/2021 11:57:04 AM.637] LSPD First Response: Exception message: Operation is not valid because the specified  Rage.Ped is invalid.
[7/6/2021 11:57:04 AM.637] LSPD First Response: ------------------------------
[7/6/2021 11:57:04 AM.637] LSPD First Response: Inner exceptions:
[7/6/2021 11:57:04 AM.637] LSPD First Response: ------------------------------
[7/6/2021 11:57:04 AM.637] LSPD First Response: Stack trace:
[7/6/2021 11:57:04 AM.637] LSPD First Response: at Rage.Entity.get_Position()
[7/6/2021 11:57:04 AM.637] at akRZfXiVWjUGFCPQSpoZDNuYiGvD.hphdYwnbkiWhmVJpIzyZAKdVrEqp() in E:\GTA V\LSPD First Response\LSPD First Response\Engine\Scripting\Tasks\TaskWatchEvent.cs:line 42
[7/6/2021 11:57:04 AM.637] at daFlJXJWpdCgjyxDCQZyqrwmXyrg.FsFglCalVSFdGhFgluLqcLbHDcKLB(BcfXTkXOFCwXijuOnjPFOMzNItkM , ZDSeomUQgUkOoHfgUevcaacCWiJcA ) in E:\GTA V\LSPD First Response\LSPD First Response\Engine\Scripting\Tasks\PedTaskManager.cs:line 98
[7/6/2021 11:57:04 AM.637] at xbixjsPXbsCoqTxLCORnwTWhegas.FYnqWWDUvuxafqtpVWnZSAZRRrbL.VGvTDMIBJElEWLDCbZbzkMZLSvyg(Object[] )
[7/6/2021 11:57:04 AM.637] at LMS.Common.Timers.DelayedCaller.Process()
[7/6/2021 11:57:04 AM.637] at XewooLvRwdsokdSyJbTjijigMCwS.DKkWaFEcaeGXTbQKRmxLHOAefPiKA() in E:\GTA V\LSPD First Response\LSPD First Response\Engine\Main.cs:line 54
[7/6/2021 11:57:04 AM.637] at GRxkwxIzOmBdUTAArpwdmaFPFpBIA.uAumHPxmifvKJTrTNpFkoCBABTOfA() in E:\GTA V\LSPD First Response\LSPD First Response\Mod\LSPDFR.cs:line 799
[7/6/2021 11:57:04 AM.637] at Rage.GameFiber.Main()
[7/6/2021 11:57:04 AM.637] LSPD First Response: ==============================
[7/6/2021 11:57:04 AM.637] LSPD First Response: 
[7/6/2021 11:57:04 AM.641] LSPD First Response: [FATAL] Forced termination
[7/6/2021 11:57:04 AM.642] LSPD First Response: [TRACE] Released 0 entities from DefaultContentManager
[7/6/2021 11:57:04 AM.642] LSPD First Response: [WARN] Chase still active, terminating manually
[7/6/2021 11:57:04 AM.642] LSPD First Response: [TRACE] Ending chase
[7/6/2021 11:57:04 AM.642] LSPD First Response: [TRACE] Aborting EvadeCops: Freeing suspect
[7/6/2021 11:57:04 AM.642] LSPD First Response: [TRACE] Aborting EvadeCopsInVehicle: Aborting main task
[7/6/2021 11:57:04 AM.644] LSPD First Response: [TRACE] TaskEvadeCopsAdvInVehicle::OnAbort
[7/6/2021 11:57:04 AM.644] LSPD First Response: [TRACE] Aborting CopChaseVisualCheck: Suspect freed
[7/6/2021 11:57:04 AM.644] LSPD First Response: [TRACE] ChaseHost #1: Suspect left chase
[7/6/2021 11:57:04 AM.644] LSPD First Response: [TRACE] Removing ped from ChaseHost #1 (GameplayMandatory)
[7/6/2021 11:57:04 AM.645] LSPD First Response: [TRACE] ChaseHost: Lost control over Paul White
[7/6/2021 11:57:04 AM.645] LSPD First Response: [TRACE] Suspect freed
[7/6/2021 11:57:04 AM.645] LSPD First Response: [TRACE] Asked thread ChaseHost #1 to abort: Chase has ended
[7/6/2021 11:57:04 AM.645] LSPD First Response: [TRACE] Released 0 entities from ChaseHost #1 Content Manager
[7/6/2021 11:57:04 AM.645] LSPD First Response: [TRACE] Instance cleaned (ChaseHost #1)
[7/6/2021 11:57:04 AM.645] LSPD First Response: [TRACE] cobkkyKsskBhBYhXcuNPlBHPDrukA is ending already
[7/6/2021 11:57:04 AM.646] LSPD First Response:    at System.Environment.GetStackTrace(Exception e, Boolean needFileInfo)
[7/6/2021 11:57:04 AM.646] at System.Environment.get_StackTrace()
[7/6/2021 11:57:04 AM.646] at LSPD_First_Response.Engine.BaseComponent.rinMfyMapFoIZeBXRLiieSdtbYnN() in E:\GTA V\LSPD First Response\LSPD First Response\Engine\BaseComponent.cs:line 66
[7/6/2021 11:57:04 AM.646] at GuRbJIYHXiaBrkxsWLEMiGkZyUIY.guKWEoYNvwkXLQlfXLzheGCpkQFk() in E:\GTA V\LSPD First Response\LSPD First Response\Mod\ChaseHost.cs:line 82
[7/6/2021 11:57:04 AM.646] at LSPD_First_Response.Engine.BaseComponent.rinMfyMapFoIZeBXRLiieSdtbYnN() in E:\GTA V\LSPD First Response\LSPD First Response\Engine\BaseComponent.cs:line 68
[7/6/2021 11:57:04 AM.646] at ikBDNnHoMrfPNjWcvdRwVjpSLupaA.KufpjGuJMiRIDYRWvpFXCxLJjaZw(String ) in E:\GTA V\LSPD First Response\LSPD First Response\Engine\Scripting\ThreadedScriptComponent.cs:line 52
[7/6/2021 11:57:04 AM.646] at GuRbJIYHXiaBrkxsWLEMiGkZyUIY.ilnELrIZNLyscPGuMNcLEqMRRPgtA(cobkkyKsskBhBYhXcuNPlBHPDrukA ) in E:\GTA V\LSPD First Response\LSPD First Response\Mod\ChaseHost.cs:line 105
[7/6/2021 11:57:04 AM.646] at cobkkyKsskBhBYhXcuNPlBHPDrukA.guKWEoYNvwkXLQlfXLzheGCpkQFk() in E:\GTA V\LSPD First Response\LSPD First Response\Engine\Scripting\Chase.cs:line 1287
[7/6/2021 11:57:04 AM.646] at LSPD_First_Response.Engine.BaseComponent.rinMfyMapFoIZeBXRLiieSdtbYnN() in E:\GTA V\LSPD First Response\LSPD First Response\Engine\BaseComponent.cs:line 68
[7/6/2021 11:57:04 AM.646] at GRxkwxIzOmBdUTAArpwdmaFPFpBIA.oqVjyOUsadRSLRkHxCXbZLVLiWFg() in E:\GTA V\LSPD First Response\LSPD First Response\Mod\LSPDFR.cs:line 782
[7/6/2021 11:57:04 AM.646] at ARvEPtUyiLsRMjuZCeQjbYaJhBJV.mNeoAXHFrYLdCYLGeitTBnEmiSinA(Action , Action ) in E:\GTA V\LSPD First Response\LSPD First Response\Engine\Common.cs:line 402
[7/6/2021 11:57:04 AM.646] at GRxkwxIzOmBdUTAArpwdmaFPFpBIA.OnUnload(Boolean isTerminating) in E:\GTA V\LSPD First Response\LSPD First Response\Mod\LSPDFR.cs:line 737
[7/6/2021 11:57:04 AM.646] at Rage.RemotePlugin.ExecuteExitPoint(Boolean isTerminating)
[7/6/2021 11:57:04 AM.646] LSPD First Response: [TRACE] Pursuit has ended, finishing stage
[7/6/2021 11:57:04 AM.647] LSPD First Response: [TRACE] InvokeFinished: Stage CrimeStageEncounterInVehicle finished
[7/6/2021 11:57:04 AM.647] LSPD First Response: [TRACE] StageOnFinished
[7/6/2021 11:57:04 AM.647] LSPD First Response: [TRACE] CurrentStage_Finished: CrimeStageEncounterInVehicle finished
[7/6/2021 11:57:04 AM.648] LSPD First Response: [TRACE] CurrentStage_Finished: CrimeStageEncounterInVehicle was final stage
[7/6/2021 11:57:04 AM.648] LSPD First Response: [TRACE] Finishing crime Cold cases
[7/6/2021 11:57:04 AM.648] LSPD First Response: [TRACE] Finishing all logic for Paul White
[7/6/2021 11:57:04 AM.649] LSPD First Response: [TRACE] Crime finished
[7/6/2021 11:57:04 AM.649] LSPD First Response: [TRACE] Released 0 entities from Chase #1 Content Manager
[7/6/2021 11:57:04 AM.649] LSPD First Response: [TRACE] Instance cleaned (Chase #1)
[7/6/2021 11:57:05 AM.858] LSPD First Response: [INFO] LSPDFR has shut down
[7/6/2021 11:57:06 AM.530] LSPD First Response: All signs removed
[7/6/2021 11:57:06 AM.619] LSPD First Response: UB All Police Partners are removed
[7/6/2021 11:57:06 AM.739] LSPD First Response: UB All Police Buddy are removed
[7/6/2021 11:57:06 AM.744] LSPD First Response: UB: UNIT FULLY DISMISSED >> OSB-0 | TOTAL ACTIVE UNIT >> 0
```

**Comment by sEbi3** [comment]
Hi, thank you for reporting the crash.
It's a known issue with UC. I'm going to release an update soon with a fix for this.
